########### Admin/Import/Etc ###########
from intuitlib.client import AuthClient
#from intuit.oauth.client import AuthClient #### I had to downloat intuitlin-oath library did you? 
#from intuit.oauth.scopes import Scopes
import utilities

########### Deliverable ###########S

testapp_A1_id = 'ABchHIpAAjp78EEGlZi5dBPIm7K58g2TAU8H1lhRPV0SmdzsLS'
testapp_A1_sec = 'hyAj3l4voHCgfV7L8yueq8KGe4zcKji6pzu3ar6j'

auth_client = AuthClient(
        client_id= testapp_A1_id, #generated by Intuit
        client_secret= testapp_A1_sec, #generated by Intuit
        environment='sandbox', 
        redirect_uri='https://developer.intuit.com/v2/OAuth2Playground/RedirectUrl', #provided by Intuit
    )

scopes = [
    ''
    ''
]

########### Main ###########
def main():
    pass

if __name__ == '__main__':
    main()